from __future__ import annotations

PLUGIN_NAME = "quotes"
SCHEMA_VERSION = 3
DATABASE_SCHEMA_VERSION = 3
DATABASE_FILENAME = "quotes.sqlite3"
DUPLICATE_IMAGE_MESSAGE = "语录图片已存在"
DUPLICATE_QUOTE_MESSAGE = "语录内容已存在"
UPLOAD_SUCCESS_PROMPT = "我学会啦，来问问我吧！高性能ですから~"
GROUPS_DIRNAME = "groups"
IMAGES_DIRNAME = "images"
MEDIA_DIRNAME = "media"
CACHE_DIRNAME = "cache"
IMAGE_INDEX_FILENAME = "image_index.json"
MEDIA_INDEX_FILENAME = "media_index.json"
SENT_INDEX_FILENAME = "sent_index.json"
QUOTES_FILENAME = "quotes.json"
LEGACY_QUOTES_BAK_SUFFIX = ".bak"
DEFAULT_DHASH_THRESHOLD = 4
DEFAULT_DHASH_SIZE = 8
DEFAULT_ASPECT_RATIO_TOLERANCE = 0.08
MAX_SENT_RECORDS = 200
IMAGE_POOL_MAX_EDGE = 2560
IMAGE_POOL_MAX_BYTES = 1536 * 1024
IMAGE_POOL_JPEG_QUALITY = 86
